#!/bin/sh

# set -x 

#=========================================================
#=========================================================
# our configuration
#=========================================================
#=========================================================

# MYNAME=allka.wyae.de
MYNAME=www.lorax.org
MYDOM=lorax.org
MYGROUP="Server"	# Leave unset to lookup via DNS TXT

WEBURL="http://$MYNAME/mosshe/"
WWWDIR=/var/www/html/mosshe
DATADIR=/etc/mosshe
TEMPDIR=/tmp

NETWAIT=10	# seconds timeout for network service check


#=========================================================
# Startup
#=========================================================
. $DATADIR/functions.mosshe

MossheSelfCheck page-lorax@lorax.org	# send alert to - if MoSShE has a problem



#=========================================================
# local info-shows
#=========================================================
# . $DATADIR/functions.localshows

# PS1Show
# HostNotesShow
# SysInfoShow
# IfconfigShow
# PstreeShow
# RouteShow
# DfShow
# WShow
# UptimeShow
# FreeShow
# NetstatShow
# PackagesShow
# LastLoginShow




. $DATADIR/functions.netchecks

. $DATADIR/checks/lorax-local

. $DATADIR/checks/ns1-remote
. $DATADIR/checks/ns2-remote
# . $DATADIR/checks/lorax-remote
#. $DATADIR/checks/dev-remote
#. $DATADIR/checks/devnew-remote



#=========================================================
# Import agent data from other servers
#=========================================================

#------  pull 

# ImportAgent http://www.test.test/mosshe/index.csv
# ImportAgentCurl http://username:password@example.com/mosshe/index.csv



#=========================================================
# Finalize and send alert if necessary
#=========================================================
FinalizeLog 0	# always needed (provide a true value to rm -f $WWWDIR/*.html

SortGroups	# optional group-list & per-group-listing

SortServers	# yes, we want e per-server listing (optional)

# RRD processing of logs - without graphs, just plain data
#ProcessRRD


#---------------------------------------------
# send alerts

AlertProwlOnPersistentNotok 3			# send alert to - if status changes

# AlertMailAlways root@example.test		# send alert to - repeated, if status not OK

# send alert if status changes for the system given (here: www.example.com)
# AlertMailOnChangeFor www.example.com admin@example.com "Ticket 123456: server outages"

SyslogOnChange local0				# syslog changes to syslog with FACILITY (default: local0)



#---------------------------------------------
# do logging

# LogTo /var/log/mosshe/mosshe.log	# continuously log to filename
# LogToDaily /var/log/mosshe/mosshe_log	# continuously log to filename, date is appended automatically
# LogToMonthly /var/log/mosshe/mosshe_log	# continuously log to filename, month is appended automatically

LogToWeekly /var/log/mosshe/mosshe_log	# continuously log to filename, week is appended automatically


# evaluate single services for availability
SLA_Eval www.lorax.org HTTPheadermatch_200

# graph data
#       800 pixel = 800 x 5min = 66.6h = 2d 18.6h
#       1 week = 168h    @ 5 min = 2016 datapoints
PlotDataFiles  2016

# mosshe_averagegraph
# average 12 @ 5min = 1h
#       every hour  @800pixel    = 33.25d = 1 month
#       every hour  over 1 week = 12 weeks = 3 months - here doubled = 6 months
PlotAvgDataFiles 12 4032

#############################################################################
# MoSSHe: remote server monitoring environment
#
# Copyright (C) 2003- Volker Tanger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# For bug reports and suggestions or if you just want to talk to me please
# contact me at volker.tanger@wyae.de
#
# Updates will be available at  http://www.wyae.de/software/mosshe/
# please check there for updates prior to submitting patches!
#
# For list of changes please refer to the HISTORY file. Thanks.
#############################################################################

