#!/bin/sh
GIT_SSH=./ssh-mosshe

# ns1 -> QuickWeb
hg push -e 'ssh -i /Users/lorax/.ssh/id_rsa.tinydns' -f ssh://tinydns@199.195.141.75//usr/local/lib/mosshe

# ns2 -> BuyVM
hg push -e 'ssh -i /Users/lorax/.ssh/id_rsa.tinydns' -f ssh://tinydns@205.185.123.6//usr/local/lib/mosshe

#lorax -> EC2
git push ssh://mosshe@54.164.125.117//usr/local/mosshe davidsoergel
