#!/bin/sh

MYGROUP="HTTP"

HTTPheader https://davidsoergel.com

HTTPcontentmatch https://davidsoergel.com/ "RSS feed"
HTTPcontentmatch https://davidsoergel.com/posts/visualizing-a-todo-list-with-treemaps "visualize"
# HTTPcontentmatch http://davidsoergel.com/jenkins/ "Jenkins"
# HTTPcontentmatch http://davidsoergel.com/nexus/content/groups/public/ "repository.xml"
