#!/bin/sh

MYGROUP="PING"

# Can't ping into EC2, but the other checks should catch a problem
#PingTime www.lorax.org 3 300 1000	# IP, NumberOfPings, max roundtrip ms WARN, ALERT
#PingLoss www.lorax.org 3 50 99	# IP, NumberOfPings, max% Loss WARN, ALERT

MYGROUP="SSH"

SSHcheck www.lorax.org

MYGROUP="HTTP"

HTTPheader https://www.lorax.org
HTTPcontentmatch https://www.lorax.org "folks"
HTTPcontentmatch https://www.dsoergel.com "Freiburg"

MYGROUP="MoSSHe"

HTTPcontentmatch http://www.lorax.org/mosshe/index.html "MoSSHe System Status"